### ISSUE TITLE
Callback without the event object

### ISSUE THREAD

**Issue by cosminonnet** [cowboy/jquery-tiny-pubsub#1]
Hi,

I was looking for a simple Pub/Sub system to use with jQuery/jQuery UI and I found "jquery-tiny-pubsub", which is great. However, I don't really like that the functions are called with an event object as first argument.

In your example, you say : "// Skip the first argument (event object) but log the name and other args.".
## My example:

```
$.publish("msg", 5);

$.widget('myWidget', {
    _create: function () {
        var self = this;            
        $.subscribe("msg", $.proxy(self, "_handleRecieve"));
    },  
    _handleRecieve: function (event, value) {
        this.element.append("<p>" + value + "</p>");
    }
});
```

I don't want the signature of the "_handleRecieve" method to be "function (event, value) ", but "function (value)", because the "event" it's never used.

Therefore, I rewrote the method "subscribe" as I follows:

```
  $.subscribe = function() {
    var events, handler, handlerWrapper;

    events = arguments[0];
    handler = arguments[1];
    handlerWrapper = function(event) {
    return handler.apply(this, Array.prototype.slice.call(arguments, 1));
    };

    o.on.call(o, events, handlerWrapper);
  };
```

I would like to know your oppinion on this implementation. Are there any downsides?

**Comment by cowboy** [comment]
I did something like this in [a previous iteration](https://gist.github.com/661855/2c518edd29b744d04bff55ec9a2a5d12afe41595) but didn't like it because it made the code too large.

**This is a _tiny_ pub/sub plugin, not a _good_ pub/sub plugin.**

**Comment by cosminonnet** [comment]
Thank you for your answer, I really appreciate.

I will use this slightly modified version because I don't want the callback methods to have the "event" object as first argument (in case I decide later on to change the Pub/Sub implementation).

I'll have to assign "handlerWrapper.guid" property as you did in your previous version of the plugin in order to respect the jQuery guidelines.

Thanks again!

**Comment by zaus** [comment]
@cosminonnet: I actually think including the event is helpful, especially with debugging, because it helps you to track down and identify what's happening.  Consider the basic development scenario where attach a generic logging function to every published call -- i.e. `console.log(event, arguments)` -- rather than customizing the logger for each call, which allows you to list what's getting triggered.
